- spy/__main__.py
- spy/errors.py
- spy/irgen/legacy_codegen.py
- spy/parser.py
- spy/tests/compiler/test_basic.py
- spy/tests/support.py
- spy/tests/test_parser.py
- spy/tests/test_scope.py
This augments expect_errors with the ability of checking also the precise piece of source code which is pointed by each annotation.
> More precise expect_errors

- spy/irgen/modgen.py
- spy/tests/compiler/test_basic.py
- spy/vm/astframe.py
- spy/vm/varstorage.py
The ASTFrame is a dynamic interpreter, but the semantics of SPy requires that some operations are dispatched using their static types.
This PR introduces FrameVal, which is a small wrapper arund W_Object to keep track of the static types.
> Keep track of static types in AST frames

- spy/irgen/irgen.py
- spy/irgen/legacy_codegen.py
- spy/irgen/legacy_typechecker.py
- spy/irgen/modgen.py
- spy/irgen/symtable.py
- spy/tests/compiler/test_debug.py
- spy/tests/compiler/test_modules.py
- spy/tests/support.py
- spy/tests/test_typechecker.py
- spy/vm/astframe.py
- spy/vm/typechecker.py
- spy/vm/vm.py
The ASTFrame was becoming messy, because it contained logic to evaluate the expressions (thus propagating their dynamic types) AND to do typechecking (which must use the static types).
This PR clearly split the logic into two:
- the job of the ASTFrame is to evaluate expressions
- the job of the typechecker is to compute and keep track of the static types
The main difference w.r.t. the legacy typecheker is that the new one operates on a per-function basis, instead of the whole module. This is needed because with blue/generic functions, type annotations are not known until runtime/doppler time.
The other advantage is that when we will implement the doppler, we should be able to reuse the typechecker
> Re-introduce the typechecker

- spy/ast.py
- spy/irgen/scope.py
- spy/irgen/symtable.py
- spy/location.py
- spy/tests/compiler/test_basic.py
- spy/tests/test_scope.py
- spy/vm/astframe.py
- spy/vm/typechecker.py
- Kill Typechekr.locals_loc: it's not longer needed since we now have funcdef.symtable
- finally re-enable more precise error messages for function calls: now we include again the Loc where the function was defined
> Refactor type locs

- requirements.txt
- spy/ast.py
- spy/ast_dump.py
- spy/backend/c/cwriter.py
- spy/irgen/scope.py
- spy/magic_py_parse.py
- spy/parser.py
- spy/tests/compiler/test_basic.py
- spy/tests/test_backend_c.py
- spy/tests/test_magic_py_parse.py
- spy/tests/test_parser.py
- spy/tests/test_scope.py
- stubs/_ast.pyi
global variables are by default const and blue, but this PR makes it possible to declare them `var`, and thus they become red.
The hard part was to add support to it to the parser, see the long docstring inside `magic_py_parser.py`.
> Add support for `var` globals

- spy/backend/c/c_ast.py
- spy/backend/c/cwriter.py
- spy/doppler.py
- spy/tests/compiler/test_basic.py
Now that we support var globals, we can unskip and fix some tests.
> Progress in fixing the C backend

- spy/doppler.py
- spy/tests/compiler/test_basic.py
- spy/tests/support.py
- spy/vm/astframe.py
- spy/vm/typechecker.py
Type errors can be reported lazily (at runtime, e.g. in case of the interp backend) or eagerly  (at compile time, e.g. for doppler and C backends).
This PR introduces a new pattern for being able to test all the desired cases.
Moreover, it fixes doppler to eager typechecks for local variables and return types. This allows to unskip some tests.
> New pattern for testing type errors

- spy/ast.py
- spy/backend/c/cwriter.py
- spy/backend/spy.py
- spy/doppler.py
- spy/irgen/modgen.py
- spy/parser.py
- spy/tests/test_backend_spy.py
- spy/tests/test_doppler.py
- spy/tests/test_parser.py
- spy/tests/test_scope.py
- spy/vm/astframe.py
`ast.VarDef` now represents only the variable declaration. The initialization is rendered as a separate `ast.Assign` node.
This should hopefully make astframe, typechecker and doppler easier and less tangled (more PRs to come)
> Refactor vardef

- spy/tests/compiler/test_basic.py
- spy/tests/vm/test_vm.py
- spy/vm/astframe.py
- spy/vm/typechecker.py
- spy/vm/typeconverter.py
- spy/vm/vm.py
This simplifies a lot of things in the dance between the typechecker, the astframe and (later) the doppler:
- whenever the typechecker expects an exception of a certain type, it calls convert_type_maybe
- convert_type_maybe can "attach" a TypeConverter to the expression, in case it's needed
- if the type conversion cannot be done, we raise a SPyTypeError. This simplifies a lot of the old code and reduce code duplication
- the astframe no longer needs to deal with implicit conversions which were assumed to exist by the typechecker: it can assume that the types of objects are always correct
We can use the new mechanism to implement conversions to and from `object`: everything can be converted to `object` and it always succeed. `object` can be converted to anything, but it will introduce a …
> Introduce type converters

- spy/ast.py
- spy/backend/c/cwriter.py
- spy/backend/spy.py
- spy/doppler.py
- spy/libspy/include/spy/str.h
- spy/libspy/src/str.c
- spy/tests/compiler/test_basic.py
- spy/tests/test_libspy.py
- spy/vm/astframe.py
- spy/vm/ops.py
- spy/vm/str.py
- spy/vm/typechecker.py
This is a big refactoring, and it's a big step towards the final idea of how SPy works.
Until now `+`, `*` and `[]` where handled with ad-hoc code in the typecheker, astframe e C backend, doing different things depending on the types.
Now, we have a generic mechanism for operation dispatching: basically, for each operator we have a builtin `@blue` function which selects the concrete implementation given the input types. In other words:
```
a + b
```
is roughly equivalent to:
```
ops.ADD(type(a), type(b))(a, b)
```
where `ops.ADD` is considered blue and thus redshifted away by the doppler.
In the next PRs, we will make `ops.ADD` & co. "real" SPy primitive functions, and use the same mechanism also for comparison ops.
> Introduce the concept of OpImpl

- spy/ast.py
- spy/backend/c/cwriter.py
- spy/backend/spy.py
- spy/doppler.py
- spy/irgen/modgen.py
- spy/libspy/include/spy.h
- spy/libspy/include/spy/str.h
- spy/tests/vm/test_vm.py
- spy/vm/astframe.py
- spy/vm/builtins.py
- spy/vm/builtins2.py
- spy/vm/function.py
- spy/vm/object.py
- spy/vm/ops.py
- spy/vm/registry.py
- spy/vm/typechecker.py
- spy/vm/vm.py
`ModuleRegistry` is the new official API to create SPy builtin modules:
- the `builtins` module is now created using this
- the opimpl are now inside the `builtins.ops` module
Thanks to `builtins.ops`, we could remove a lot of ad-hoc support for ops/opimpls: now opimpls are just standard `W_Func` (all of them implemented at interp-level for now, so `W_BuiltinFunc`).
This allows to kill the ugly `ast.HelperFunc` and simplify a lot the code here and there.
> Introduce the module registry and create builtins.ops

- spy/__main__.py
- spy/backend/c/cwriter.py
- spy/backend/spy.py
- spy/doppler.py
- spy/fqn.py
- spy/irgen/modgen.py
- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_dynamic.py
- spy/tests/support.py
- spy/tests/test_doppler.py
- spy/tests/test_fqn.py
- spy/tests/vm/test_vm.py
- spy/vm/astframe.py
- spy/vm/function.py
- spy/vm/modules/operator/multimethod.py
- spy/vm/modules/operator/opimpl_dynamic.py
- spy/vm/typechecker.py
- spy/vm/vm.py
This PR does two things:
1. add support for calling expressions whose type is `dynamic`
2. add support for redshifting/compiling closures which are generated
inside @blue functions
> Support for `dynamic` calls

- spy/backend/c/context.py
- spy/backend/c/cwriter.py
- spy/backend/c/wrapper.py
- spy/doppler.py
- spy/parser.py
- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_float.py
- spy/vm/astframe.py
- spy/vm/b.py
- spy/vm/modules/operator/__init__.py
- spy/vm/modules/operator/binop.py
- spy/vm/modules/operator/opimpl_f64.py
- spy/vm/modules/operator/opimpl_i32.py
- spy/vm/object.py
- spy/vm/typechecker.py
- spy/vm/typeconverter.py
- spy/vm/vm.py
This PR adds a lot of long-needed features regarding numeric operations:
- introduce the f64 type, and add support for it a bit everywhere
- implement - and / for both i32 and f64
- introduce support for implicit conversions from i32 to f64
> Introduce the `f64` type and more numeric ops

- spy/__main__.py
- spy/tests/compiler/test_basic.py
- spy/tests/test___main__.py
- spy/vm/modules/builtins.py
- spy/vm/vm.py
This PR adds:
- a minimal implementation of print()
- the possibility of running spy --run foo.spy to run a script from the command line
> Add print() and spy --run

- spy/irgen/modgen.py
- spy/irgen/scope.py
- spy/parser.py
- spy/tests/compiler/test_basic.py
- spy/tests/test_parser.py
This adds type inference support for global vars and consts.
It is also possible to init them by calling a `@blue` function.
> Support complex expressions as initializers of global vars and consts

- spy/ast.py
- spy/backend/spy.py
- spy/doppler.py
- spy/fqn.py
- spy/irgen/modgen.py
- spy/parser.py
- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_dynamic.py
- spy/tests/test_backend_spy.py
- spy/tests/test_parser.py
- spy/vm/astframe.py
- spy/vm/module.py
- spy/vm/modules/operator/opimpl_dynamic.py
- spy/vm/modules/operator/opimpl_misc.py
- spy/vm/modules/operator/unaryop.py
- spy/vm/typechecker.py
This PR adds to big functionalities together, because it's not possible to test one without the other.
* Basic support for setattr: we add support in the parser, typechecker, etc. for setattr, which is mapped to `operator.SETATTR`. Currently, the only object which supports it is `module`, which can be modified only before it's frozen
* Support for `__INIT__`: this is a special `@blue` function which is automatically called at import time, and that modules can use to do pre-redshift initialization
> Add support for __INIT__ and basic support for setattr

- spy/backend/c/context.py
- spy/backend/c/cwriter.py
- spy/backend/c/wrapper.py
- spy/doppler.py
- spy/tests/compiler/test_typedef.py
- spy/vm/modules/operator/opimpl_misc.py
- spy/vm/modules/operator/unaryop.py
- spy/vm/modules/types.py
- spy/vm/typechecker.py
- spy/vm/vm.py
This is a breakthrough.
This PR introduces `TypeDef`, which makes it possible to define a static-type alias of another type. The big news is that you can attach custom (blue) `__getattr__` and `__setattr__` to the typedef, and these calls will be redshifted away.
It needs more polishing: currently we support implicit conversion from and to the TypeDef, but only because we don't support enough of the language to have a better way. Ideally, I would like a `cast[T]` function.
> Introduce TypeDef, and support for __getattr__ and __setattr__

- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_operator_single.py
- spy/tests/vm/test_function.py
- spy/vm/function.py
- spy/vm/modules/builtins.py
- spy/vm/modules/operator/binop.py
- spy/vm/modules/operator/opimpl_dynamic.py
- spy/vm/modules/operator/opimpl_f64.py
- spy/vm/modules/operator/opimpl_i32.py
- spy/vm/modules/operator/opimpl_misc.py
- spy/vm/modules/operator/opimpl_str.py
- spy/vm/modules/operator/unaryop.py
- spy/vm/modules/rawbuffer.py
- spy/vm/modules/types.py
- spy/vm/object.py
- spy/vm/registry.py
- spy/vm/vm.py
- spy/vm/w.py
`@spy_builtin` makes it possible to automatically wrap an interp-level function into an app-level function, and `vm.wrap()` works. The signature is automatically inferenced from the interp-level annotation.
This makes it possible to kill `ModuleRegistry.primitive`, which required to explicitly write the signature as a string.
> Introduce the @spy_builtin decorator

- spy/tests/compiler/test_operator_single.py
- spy/vm/function.py
- spy/vm/module.py
- spy/vm/modules/operator/__init__.py
- spy/vm/modules/operator/opimpl_misc.py
- spy/vm/modules/operator/unaryop.py
- spy/vm/modules/types.py
- spy/vm/object.py
- spy/vm/w.py
They cause more troubles than advantages.
The main reason for having them was to implement W_Module.op_GETATTR, but now we can use @spy_builtin instead.
> Kill the generic versions of opimpl_getattr and opimpl_setattr

- spy/backend/c/cwriter.py
- spy/backend/c/wrapper.py
- spy/backend/spy.py
- spy/doppler.py
- spy/fqn.py
- spy/irgen/modgen.py
- spy/irgen/scope.py
- spy/libspy/include/spy/builtins.h
- spy/libspy/include/spy/rawbuffer.h
- spy/libspy/include/spy/str.h
- spy/libspy/src/builtins.c
- spy/parser.py
- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_operator_attr.py
- spy/tests/compiler/test_typedef.py
- spy/tests/test_backend_spy.py
- spy/tests/test_fqn.py
- spy/tests/test_scope.py
- spy/tests/vm/test_function.py
- spy/tests/vm/test_module.py
- spy/tests/vm/test_vm.py
- spy/vm/astframe.py
- spy/vm/function.py
- spy/vm/module.py
- spy/vm/modules/builtins.py
- spy/vm/modules/operator/attrop.py
- spy/vm/registry.py
- spy/vm/vm.py
Split the old FQN into two different types:
A Qualified Name (QN) locates a function or class inside the source code, e.g. `test::foo`.
A Fully Qualified Name (FQN) can exists only in the context of a specific VM and must be unique. You can have multiple FQNs mapping to the same QN, e.g. in case of closures: `test::foo#0`, `test::foo#1`, etc.
Among the other things, this makes much easier to write OPERATORS at interp level, because now we can just return an interp-level closure with a QN, and the doppler will take care of turning it into an FQN when appropriate.
> Introduce the distinction between QN and FQN

- spy/tests/compiler/test_operator.py
- spy/tests/support.py
- spy/vm/typechecker.py
This PR is a huge improvement in code quality and simplification.
The typechecking code for calls and opimpls was very similar, both in concrete and in principle. The big difference is that for calls we can provide better diagnostics.
This PR make sure that we use the same code for both: by doing so, we also ensure that we do proper typecking on the opimpls returned by operators.
> Refactor typechecking of calls and operators

- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_list.py
- spy/tests/compiler/test_operator_call.py
- spy/vm/astframe.py
- spy/vm/list.py
- spy/vm/modules/operator/__init__.py
- spy/vm/modules/operator/callop.py
- spy/vm/object.py
- spy/vm/typechecker.py
Ideally, we would like to be able to call functions by just using their CALL operator, but this is not supported yet. To make it practical, for now we just special-case functions.
> Introduce the CALL operator

- .gitignore
- spy/tests/compiler/test_operator.py
- spy/tests/compiler/test_operator_attr.py
- spy/tests/compiler/test_operator_call.py
- spy/tests/vm/test_function.py
- spy/tests/vm/test_sig.py
- spy/vm/function.py
- spy/vm/list.py
- spy/vm/module.py
- spy/vm/modules/operator/attrop.py
- spy/vm/object.py
- spy/vm/registry.py
- spy/vm/sig.py
- spy/vm/str.py
- spy/vm/typechecker.py
- spy/vm/w.py
Make it possible to call types to instantiate them.
In order to do this, we need to create a corresponding metaclass for each type. For example:
```
class W_Foo(W_Object):
...
```
automatically creates `W_MetaFoo(T_Type)`. See the docstring of `create_metaclass` for more details.
> Add support for instantiating types via CALL operator

- requirements.txt
- spy/__main__.py
- spy/backend/c/wrapper.py
- spy/cbuild.py
- spy/compiler.py
- spy/libspy/Makefile
- spy/libspy/__init__.py
- spy/libspy/include/spy.h
- spy/libspy/include/spy/builtins.h
- spy/libspy/include/spy/debug.h
- spy/libspy/src/builtins.c
- spy/libspy/src/debug.c
- spy/libspy/src/str.c
- spy/llwasm.py
- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_rawbuffer.py
- spy/tests/support.py
- spy/tests/test___main__.py
- spy/tests/test_libspy.py
- spy/tests/test_llwasm.py
wasm32-freestanding would be cool but it creates too many challenges for now.
It is easier to just support WASI and be able to rely on a libc.
This PR also updates the required version of zig, which in turn is more stricter about exported symbols.
Note that for now, we do NOT support creating wasi standalone executable: wasi is used only in "reactor mode" to compile our tests.
It should be easy to add support for executables in the future, but it would probably require a refactoring of `cbuild.py` and the concept of toolchain/targets.
> Target WASI instead of wasm32-freestanding

- spy/backend/c/cwriter.py
- spy/doppler.py
- spy/libspy/include/spy/str.h
- spy/libspy/src/str.c
- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_operator_call.py
- spy/vm/str.py
...but in order to do that, we had to improve several things. In particular, now op.CALL can return an opimpl, and the doppler now needs to support it.
It turns out that `test_operator_call::test_call_instance` needs that logic, but earlier it was passing "by chance" because the blue call was not redshifted aways and thus was still present (and the interpreter was able to run that).
> Add support for str(i32)

- spy/ast.py
- spy/backend/spy.py
- spy/doppler.py
- spy/parser.py
- spy/tests/compiler/test_operator_call.py
- spy/tests/test_backend_spy.py
- spy/tests/test_parser.py
- spy/vm/astframe.py
- spy/vm/modules/operator/callop.py
- spy/vm/object.py
- spy/vm/typechecker.py
This is a bit of a departure from the standard Python semantics but I believe it makes many common patterns easier to write (and possibly more efficient).
Normally, the pattern `a.b(...)` is parsed as a `Call(GetAttr(), ...)`, but with this PR we special-case this syntax and we produce `CallMethod(...)`. Objects can then implement their own operator to implement it.
This will be useful for example to implement a Javascript FFI, because JS doesn't have the concept of bound methods.
In the future, we will probably implement a default `CALL_METHOD` which is implemented in terms of getattr+call.
> Introduce CALL_METHOD as a 1st-class operator

- spy/tests/compiler/test_basic.py
- spy/vm/bluecache.py
- spy/vm/modules/operator/__init__.py
- spy/vm/modules/operator/binop.py
- spy/vm/modules/operator/opimpl_dynamic.py
- spy/vm/modules/operator/opimpl_object.py
- spy/vm/object.py
- spy/vm/vm.py
This PR introduces the concepts of "storage categories" and "universal equality".
As a result, we are able to fix one of the 3 "FIXME" which were introduced by PR #58.
Storage category is used to distinguish between "value types" and "reference types":
- value types: (e.g. i32, f64, but also str and eventually user-defined structs) don't have the concept of identity and the operator `is` is forbidden on them (well, it will be, since `is` has not been implemented yet).
This is a departure from Python semantics, but arguably using `is` on primitive types is almost always wrong and leads to subtle bugs (such as `if x is 'hello'` or `if x is 42`, which might or might not work depending on the phase of the moon).
- reference types: objects have an identity and `is` can be used. Moreover, by …
> Introduce storage categories and universal equality

- spy/backend/spy.py
- spy/tests/compiler/test_list.py
- spy/tests/compiler/test_operator_call.py
- spy/vm/astframe.py
- spy/vm/b.py
- spy/vm/list.py
- spy/vm/modules/jsffi.py
- spy/vm/object.py
- spy/vm/typechecker.py
- spy/vm/vm.py
This PR cleans and improves the implementation of `list`.
In particular:
1. kill `ListFactory`: thanks to support for metatypes, we can now implement the app-level `list` and the interp-level `W_List`, and use `W_List.meta_op_GETITEM` to allows things like `list[i32]`.
2. kill the ugly manual `CACHE`. Now that we support blue builtins, we can rely on  standard blue caching mechanism.
> Refactor list types

- spy/tests/compiler/test_operator.py
- spy/tests/compiler/test_operator_attr.py
- spy/tests/compiler/test_operator_call.py
- spy/tests/compiler/test_typedef.py
- spy/vm/modules/jsffi.py
- spy/vm/modules/rawbuffer.py
- spy/vm/modules/types.py
- spy/vm/registry.py
Simplify and improve the usage of `ModuleRegistry`:
- add `@MOD.spytype`
- use `spy_new` everywhere and kill the ugly `make*` functions
> Improve ext modules

- spy/ast.py
- spy/ast_dump.py
- spy/backend/spy.py
- spy/irgen/scope.py
- spy/parser.py
- spy/tests/compiler/test_tuple.py
- spy/tests/test_backend_spy.py
- spy/tests/test_parser.py
- spy/vm/astframe.py
- spy/vm/b.py
- spy/vm/tuple.py
- spy/vm/typechecker.py
This PR adds basic support for tuples:
- parser support for tuple literals and unpacking assignment
- symytable/typechecker/astframe support for unpacking assignment
- a super simple W_Tuple type, which is supposed to be used only in blue code and for bootstrapping
> Add a basic tuple type

- spy/doppler.py
- spy/tests/compiler/test_list.py
- spy/tests/compiler/test_operator.py
- spy/tests/compiler/test_operator_attr.py
- spy/tests/compiler/test_operator_call.py
- spy/vm/astframe.py
- spy/vm/list.py
- spy/vm/module.py
- spy/vm/modules/jsffi.py
- spy/vm/modules/operator/attrop.py
- spy/vm/modules/operator/binop.py
- spy/vm/modules/operator/callop.py
- spy/vm/modules/operator/itemop.py
- spy/vm/modules/operator/multimethod.py
- spy/vm/modules/operator/opimpl_dynamic.py
- spy/vm/modules/types.py
- spy/vm/object.py
- spy/vm/opimpl.py
- spy/vm/str.py
- spy/vm/tuple.py
- spy/vm/typechecker.py
- spy/vm/vm.py
- spy/vm/w.py
This is a big refactoring, but doesn't add any new functionality.
Refactor the signature of `OPERATOR`s: instead of returning a function, they now return a `W_OpImpl`, which at the moment is just a simple wrapper around a function.
`W_OpImpl` will get new features later.
> Introduce W_OpImpl

- spy/doppler.py
- spy/tests/compiler/test_operator.py
- spy/tests/compiler/test_operator_attr.py
- spy/tests/compiler/test_operator_call.py
- spy/tests/support.py
- spy/vm/astframe.py
- spy/vm/list.py
- spy/vm/module.py
- spy/vm/modules/jsffi.py
- spy/vm/modules/operator/attrop.py
- spy/vm/modules/operator/binop.py
- spy/vm/modules/operator/itemop.py
- spy/vm/modules/operator/multimethod.py
- spy/vm/object.py
- spy/vm/opimpl.py
- spy/vm/str.py
- spy/vm/tuple.py
- spy/vm/typechecker.py
- spy/vm/vm.py
This is a big refactoring in how OPERATORS, the vm and the typechecker play all together.
Old-style operators receive argument types, and return a function to be called on those arguments.
New-style operators receive abstract "Values", which also have a type but also represent a placeholder for the actual values which will be computed at runtime. They can decide to pass these Values in any order to the opimpl, but also discard them, or in the future to add type conversions, etc.
Contrarily to old-style, it's the job of new-style operators to raise a proper `SPyTypeError`.
This ensures that you get high-quality errors even at runtime (e.g. by calling `vm.getitem` or so). 
Compile-time type errors are no longer explicitly raised by the typechecker, but naturally come from redshifting blue …
> Introduce W_OpImpl.with_values

- spy/tests/compiler/test_jsffi.py
- spy/tests/compiler/test_operator.py
- spy/tests/compiler/test_operator_attr.py
- spy/tests/compiler/test_operator_call.py
- spy/tests/compiler/test_typedef.py
- spy/vm/list.py
- spy/vm/module.py
- spy/vm/modules/jsffi.py
- spy/vm/modules/operator/attrop.py
- spy/vm/modules/operator/itemop.py
- spy/vm/modules/operator/opimpl_dynamic.py
- spy/vm/object.py
- spy/vm/opimpl.py
- spy/vm/str.py
- spy/vm/tuple.py
- spy/vm/typechecker.py
Migrate SETATTR, GETATTR, GETITEM and SETITEM to be new-style op.
This breaks jsffi because automatic type conversions are not yet supported, they will come in the next PR.
> Migrate SETATTR, GETATTR, GETITEM and SETITEM.

- spy/__main__.py
- spy/backend/spy.py
- spy/doppler.py
- spy/errors.py
- spy/tests/compiler/test_operator_attr.py
- spy/vm/astframe.py
- spy/vm/list.py
- spy/vm/modules/operator/__init__.py
- spy/vm/modules/operator/binop.py
- spy/vm/modules/operator/multimethod.py
- spy/vm/modules/operator/opimpl_dynamic.py
- spy/vm/object.py
- spy/vm/opimpl.py
- spy/vm/typechecker.py
- spy/vm/vm.py
This is another big refactoring.
All the binops are now migrated to be new-style operators, taking W_Value instead of W_Type as inputs.
This required a big of refactorings here and there, mostly around op.EQ and op.UNIVERSAL_EQ, which need special care to avoid infinite recursion.
Moreover, we made W_OpImpl.w_func private, to ensure that everybody to the actual execution by doing w_opimpl.call: this ensures that arguments are correctly reordered.
The only exceptions are op.CALL and CALL_METHOD, which are still using the old mechanism and will be refactored soon.
> Make op.ADD and all other binops new-style

- spy/backend/c/cwriter.py
- spy/doppler.py
- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_jsffi.py
- spy/tests/compiler/test_operator_call.py
- spy/tests/support.py
- spy/vm/astframe.py
- spy/vm/modules/jsffi.py
- spy/vm/modules/operator/callop.py
- spy/vm/object.py
- spy/vm/opimpl.py
- spy/vm/str.py
- spy/vm/typechecker.py
- spy/vm/typeconverter.py
- spy/vm/vm.py
These are the last two operators that needed to be turned into new-style.
Other highlights:
- thanks to W_Values, we can now remove the first unused arg from int2str. This lets us to kill a special case in the C backend
- type conversions now works again, both in interp and doppler mode: this lets us to unskip a JSFFI test
- we can finally kill `TypeChecker.opimpl_typecheck`, which is completely superseded by the new `typecheck_opimpl` (which will be probably moved inside `W_OpImpl` eventually)
> Make op.CALL and op.CALL_METHOD new-style

- examples/jsffi/make.sh
Hi @antocuni , awesome project! 🙇 🥇 🎉 
I'm wondering if you'd be willing to accept this PR?  I'd also wonder about other changes to this script, such as:
After:
```sh
emcc $CFLAGS raw_c_demo.c -o raw_c_demo.js
```
What if we add the following?
```sh
cd "$SCRIPT_DIR"
```
That way, the relative paths below the `emcc` would work as expected (I assume).
Fixes: https://github.com/spylang/spy/issues/73
> Replace absolute path

- spy/errors.py
- spy/location.py
- spy/tests/test_loc.py
- spy/tests/vm/test_vm.py
- spy/vm/opimpl.py
- spy/vm/vm.py
`W_OpArg` used to have an optional Loc, because sometimes they are generated from interp-level code which doesn't have a direct origin in the source code.
However, this is annoying because it forces to add `Optional[Loc]` and "if loc is not None" a bit everywhere.
The solution is to always provide a Loc, possibly pointing to interp-level code.
This finally fixes mypy.
> Make Loc non-optional everywhere

- spy/backend/c/cwriter.py
- spy/backend/c/wrapper.py
- spy/backend/interp.py
- spy/backend/spy.py
- spy/fqn.py
- spy/irgen/modgen.py
- spy/irgen/scope.py
- spy/irgen/symtable.py
- spy/parser.py
- spy/tests/compiler/test_basic.py
- spy/tests/test_doppler.py
- spy/tests/test_fqn.py
- spy/tests/test_parser.py
- spy/tests/vm/test_module.py
- spy/vm/astframe.py
- spy/vm/function.py
- spy/vm/list.py
- spy/vm/module.py
- spy/vm/modules/operator/attrop.py
- spy/vm/modules/unsafe/mem.py
- spy/vm/modules/unsafe/ptr.py
- spy/vm/object.py
- spy/vm/registry.py
- spy/vm/vm.py
Until now, a QN was only `modname::attr`.
This PR generalizes it, to be able to have `arbitrarily::nested::namespaces`, and also `names<with, qualifiers>`.
> Make (F)QNs arbitrarily nestable

- spy/backend/spy.py
- spy/irgen/modgen.py
- spy/tests/compiler/test_unsafe.py
- spy/tests/test_backend_spy.py
- spy/vm/astframe.py
- spy/vm/typechecker.py
- spy/vm/vm.py
This PR makes it possible to write code like this:
```
@blue
def make_Point(T):
class Point(struct):
x: T
y: T
return Point
```
To do so, we had to teach the TypeChecker about `ClassDef`, and to refactor the way FQNs are computed for types.
In particular, we cannot compute the unique FQN lazily inside `vm.make_const`, because at that point it's too late: the FQN might have already been used e.g. to create the FQN of a pointer. The solution is to assign an unique FQN as soon as a new type is created.
For symmetry, we do the same also for `FuncDef`s.
> Make it possible to create new types inside closures

- examples/vector.spy
- spy/__main__.py
- spy/backend/c/cwriter.py
- spy/location.py
commit 0683517 introduced `Location.here`, which helps to include interp-level functions into diagnostics.
However, it turns out that using `inspect.stack()` is unbearably slow.
`Location.here()` is called continuously, every time we create a `W_OpArg` from interp-level code.
By using directly `sys._getframe` we can speedup `examples/vector.spy` by 20x 😱
> Improve performance of the SPy interpreter by 20x

- spy/tests/compiler/test_operator.py
- spy/tests/compiler/test_operator_attr.py
- spy/tests/compiler/test_operator_call.py
- spy/tests/vm/test_builtin.py
- spy/tests/vm/test_vm.py
- spy/vm/b.py
- spy/vm/builtin.py
- spy/vm/function.py
- spy/vm/list.py
- spy/vm/module.py
- spy/vm/modules/builtins.py
- spy/vm/modules/jsffi.py
- spy/vm/modules/operator/attrop.py
- spy/vm/modules/operator/binop.py
- spy/vm/modules/operator/callop.py
- spy/vm/modules/operator/itemop.py
- spy/vm/modules/operator/opimpl_dynamic.py
- spy/vm/modules/types.py
- spy/vm/modules/unsafe/mem.py
- spy/vm/modules/unsafe/ptr.py
- spy/vm/modules/unsafe/struct.py
- spy/vm/object.py
- spy/vm/primitive.py
- spy/vm/registry.py
- spy/vm/str.py
- spy/vm/tuple.py
- spy/vm/vm.py
- spy/vm/w.py
This PR is big, but most of the diff is just "moving things around".
The long term goals are to reduce circular dependencies between modules imports, and preprare the ground for killing `._w`.
Highlights:
- it is now possible to use `Annotated[W_Object, w_my_type]` for `@builtin_func` signatures. This gives a cleaner implementation of `W_Dynamic` and removes the need to lot of `@no_type_check` in generic functions such as in `ptr.py`
- `vm.b` now contains an empty `B` registry, which is populated by `objects.py`, `primitives.py`, etc. This removes a lot of circular dependencies
- kill `W_Void._w_singleton` and similar singletons for bools, notimplemented, etc.: they now live directly on `B`.
- `W_Dynamic` has been moved to `primitive.py`
- the handling of `__spy_members__` is now done by …
> Refactor builtins

- spy/tests/compiler/test_list.py
- spy/tests/compiler/test_operator_call.py
- spy/vm/astframe.py
- spy/vm/b.py
- spy/vm/function.py
- spy/vm/list.py
- spy/vm/modules/jsffi.py
- spy/vm/modules/operator/__init__.py
- spy/vm/modules/operator/callop.py
- spy/vm/modules/unsafe/ptr.py
- spy/vm/object.py
- spy/vm/opimpl.py
- spy/vm/str.py
- spy/vm/typechecker.py
This does something very similar to PR #96 , but for `list`.
By doing so, we are able to use a single `W_List` class for every specialized list, and avoid the creation of dynamic `W_MyList` subclasses.
We also greatly simplify the way we handle prebuilt list types
> Introduce W_ListType

- spy/irgen/modgen.py
- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_unsafe.py
- spy/tests/vm/test_vm.py
- spy/vm/modules/types.py
- spy/vm/vm.py
This is a big departure from Python semantics, but it's required to write types having fields which directly or indirectly reference themselves. Moreover, it makes writing type-annotated code much easier.
TL;DR, we can now do this:
```
def foo(x: MyType) -> void:
...
class MyType:
...
```
i.e., use `MyType` *before* its definition has been executed.
This is done by introducing the concept of `ForwardRef`, which is a special object which can `become()` a new object.
With these new tools, we could finally make `test_struct_with_ptr_to_itself` working, as in:
```
class Node(struct):
val: i32
next: ptr[Node]
```
> Automatic declare forward references to types

- spy/backend/c/context.py
- spy/tests/compiler/test_operator_call.py
- spy/vm/builtin.py
- spy/vm/function.py
- spy/vm/list.py
- spy/vm/modules/jsffi.py
- spy/vm/modules/operator/callop.py
- spy/vm/modules/operator/opimpl_dynamic.py
- spy/vm/object.py
- spy/vm/str.py
- spy/vm/typechecker.py
- spy/vm/vm.py
This PR makes it possible to write stuff like this:
```
@EXT.builtin_func
def w_sum(vm: 'SPyVM', *args_w: W_I32) -> W_I32:
...
```
and then we use this functionality to make the signatures of op_CALL and op_CALL_METHOD more regular, and kill `W_OpArgList`:
```
@staticmethod
def op_CALL(vm: 'SPyVM', wop_obj: 'W_OpArg',
*args_wop: 'W_OpArg') -> 'W_OpImpl':
...
@staticmethod
def op_CALL_METHOD(vm: 'SPyVM', wop_obj: 'W_OpArg', wop_method: 'W_OpArg',
*args_wop: 'W_OpArg') -> 'W_OpImpl':
...
```
> Support for *args in builtin functions

- spy/__main__.py
- spy/backend/interp.py
- spy/doppler.py
- spy/fqn.py
- spy/irgen/modgen.py
- spy/tests/compiler/test_00_bluemod.py
- spy/tests/compiler/test_list.py
- spy/tests/compiler/test_unsafe.py
- spy/tests/test_fqn.py
- spy/tests/vm/test_builtin.py
- spy/tests/vm/test_func_adapter.py
- spy/tests/vm/test_vm.py
- spy/vm/astframe.py
- spy/vm/func_adapter.py
- spy/vm/function.py
- spy/vm/modules/operator/attrop.py
- spy/vm/modules/operator/binop.py
- spy/vm/modules/operator/callop.py
- spy/vm/modules/operator/convop.py
- spy/vm/modules/operator/itemop.py
- spy/vm/modules/operator/multimethod.py
- spy/vm/modules/operator/opimpl_dynamic.py
- spy/vm/modules/unsafe/mem.py
- spy/vm/modules/unsafe/ptr.py
- spy/vm/opimpl.py
- spy/vm/typechecker.py
- spy/vm/vm.py
W_OpImpl was super messy and complicated because it served two purposes at once:
1. An high-level description of which functions to call to implement a certain OP, e.g. `W_OpImpl(w_foo)` or `W_OpImpl(w_foo, [wop_x, wop_y])`
2. A low-level description of how to actually call it: this was the messy part because `typecheck_opimpl` mutated the opimpl implace to add converters and do a whole mess with `wop.i`, and then consumers needed to check with `.is_valid()`.
The idea is to split concerns into two separate types:
1. W_OpImpl serves the same (1) purpose as before
2. The (2) is now served by `W_FuncAdapter`, which knows how to map/convert input arguments into output arguments and to call w_func.
Hopefully, soon we will also be able to kill other hacks such as `W_OpArg.i` and …
> Simplify W_OpImpl, introduce W_FuncAdapter, sanitize calling convention

- spy/ast.py
- spy/backend/c/cwriter.py
- spy/backend/spy.py
- spy/doppler.py
- spy/irgen/scope.py
- spy/parser.py
- spy/tests/test_parser.py
- spy/vm/astframe.py
- spy/vm/typechecker.py
1. Introduce `ast.StrConst`
2. use it for the following fields, instead of storing bare strings:
- `GetAttr.attr`
- `SetAttr.attr`
- `Assign.target`
- `UnpackAssign.targets`
- `CallMethod.metho`
This makes it easier to track their `loc`s, but also it will allow us to make the code in ASTFrame/doppler more uniform, because currently we have to special case these strings and turn them into proper run-time values.
> Improve parser

- spy/doppler.py
- spy/errors.py
- spy/irgen/symtable.py
- spy/location.py
- spy/tests/support.py
- spy/tests/test_loc.py
- spy/tests/vm/test_function.py
- spy/vm/astframe.py
- spy/vm/func_adapter.py
- spy/vm/function.py
- spy/vm/modules/operator/callop.py
- spy/vm/opimpl.py
- spy/vm/typechecker.py
The need for this hack was explained by this now-removed comment in `W_Func.op_CALL`:
```python
"""
This is a bit of a hack.
The correct opimpl for a W_Func object is something which says "please
just call it". Ideally, we would like to do something like that:
w_func = wop_func.blue_unwrap()
return W_OpImpl(w_func, ...)
However, we cannot because at the current moment, wop_func doesn't
carry around it's blue value: this is something which needs to be
fixed in the typechecker, eventually.
The workaround is to wrap the functype inside a special W_DirectCall
object, which is special cased by ASTFrame.
"""
```
But after #106 now we DO know the blue `w_func` at `op_CALL` time, so we can kill all the crap described there.
As a bonus point, we also put a `def_loc` attribute on every `W_Func`, so …
> Kill the ugly W_DirectCall hack

- spy/backend/spy.py
- spy/parser.py
- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_unsafe.py
- spy/tests/test_backend_spy.py
- spy/tests/test_parser.py
Change the syntax for declaring structs. Instead of:
```
class Point(struct):
x: i32
y: i32
```
we now use:
```
@struct
class Point:
...
```
This is needed because it will generalize better to the upcoming `@typedef` feature.
Eventually, once we are brave enough to modify the syntax, these might become:
```
struct Point:
...
typedef Foo:
...
```
> Struct decorator

- spy/tests/compiler/test_operator.py
- spy/tests/compiler/test_operator_attr.py
- spy/tests/compiler/test_operator_call.py
- spy/tests/vm/test_builtin.py
- spy/vm/function.py
- spy/vm/list.py
- spy/vm/module.py
- spy/vm/modules/jsffi.py
- spy/vm/modules/operator/__init__.py
- spy/vm/modules/operator/attrop.py
- spy/vm/modules/operator/callop.py
- spy/vm/modules/operator/convop.py
- spy/vm/modules/operator/itemop.py
- spy/vm/modules/types.py
- spy/vm/modules/unsafe/ptr.py
- spy/vm/object.py
- spy/vm/str.py
- spy/vm/tuple.py
- spy/vm/vm.py
Turn most of the various `op_*` methods like `op_GETITEM`, `op_GETATTR` etc into proper builtin_methods such as `w_GETITEM`, `w_GETATTR`, etc.
This is an important step to allow user-defined types, where OPERATORS can be written at app level.
The transition is still not 100% complete. In particular the following are still using the old `op_*` convention:
- `W_Func.op_CALL`
- all `op_EQ` and `op_NE`
This is because they are used by `W_Func` and/or `W_OpImpl`/`W_OpArg`, and we cannot apply `@builtin_method` to them without causing circular dependencies.
> Use @builtin_method for almost all OPERATORS

- spy/__main__.py
- spy/ast.py
- spy/irgen/scope.py
- spy/parser.py
- spy/tests/compiler/test_operator.py
- spy/tests/compiler/test_typelift.py
- spy/tests/compiler/test_unsafe.py
- spy/tests/test_parser.py
- spy/tests/test_scope.py
- spy/vm/astframe.py
- spy/vm/function.py
- spy/vm/modules/types.py
- spy/vm/modules/unsafe/struct.py
- spy/vm/opimpl.py
- spy/vm/vm.py
- parser support for method definintions inside classdef
- fix scope analyzer for class bodies
- introduce the concept of `ClassFrame`, which is a frame created specifically to executed class bodies
- add enough support here and there so that we can now create a custom `@typelift`ed type with a functions `__GETITEM__` method
> Make it possible to create functional custom types using @typelift

- spy/vm/builtin.py
- spy/vm/function.py
- spy/vm/list.py
- spy/vm/modules/operator/binop.py
- spy/vm/modules/unsafe/ptr.py
- spy/vm/object.py
- spy/vm/opimpl.py
- spy/vm/vm.py
In PR #112 we couldn't complete the migration of all `op_*` into proper `@builtin_method`s for bootstrapping reasons.
With lazy_init, we are now able to use builtin_method also for `EQ` and `NE`, and apply it to `W_OpArg` and `W_FuncType`.
> Introduce a more proper "lazy initialization" of builtin types

- spy/irgen/modgen.py
- spy/tests/compiler/test_basic.py
- spy/tests/vm/test_vm.py
- spy/vm/astframe.py
- spy/vm/builtin.py
- spy/vm/function.py
- spy/vm/list.py
- spy/vm/modules/operator/attrop.py
- spy/vm/modules/types.py
- spy/vm/modules/unsafe/ptr.py
- spy/vm/modules/unsafe/struct.py
- spy/vm/object.py
- spy/vm/opimpl.py
- spy/vm/primitive.py
- spy/vm/registry.py
- spy/vm/typechecker.py
- spy/vm/vm.py
Kill `W_ForwardRef`.
The big problem of `W_ForwardRef` is that they could work reliably only for module-level definitions (because the `.become` happened in `vm.add_global`): this means that e.g. this code:
```
@typelift
class MyClass:
__ll__: i32
def __new__(cls) -> MyClass:
...
```
worked well at module level, but crashed inside the function.
Instead, introduce a two-step type initialization mechanism: types can be in "declared" state, and then transition into a "defined" state. In the next PRs, we will use this new feature to fix the case above.
Among the other things, this plays well with the need of lazy initialization of some core types: instead of using an ad-hoc "lazy setup" mechanism, we can just use the standard declare/define split.
> Kill W_ForwardRef, introduce types declaration/definition

- spy/doppler.py
- spy/irgen/irgen.py
- spy/tests/compiler/test_basic.py
- spy/tests/vm/test_builtin.py
- spy/vm/astframe.py
- spy/vm/classframe.py
- spy/vm/modframe.py
This PR introduces `ModFrame`, which is the brother of `ASTFrame` and `ClassFrame`, and it's responsible to evaluate the content of a module.
`ModFrame` replaces the old `ModGen`, which did something similar by instantiating a fake function where to evaluate statements.
With this change we are able to share the logic to forward-declare types between ModFrame and ASTFrame, which means that now forward declaration of types work also inside a funciton.
> Introduce a proper frame type where to evaluate module content

- spy/backend/spy.py
- spy/cli.py
- spy/doppler.py
- spy/fqn.py
- spy/fqn_parser.py
- spy/tests/support.py
- spy/tests/test_doppler.py
- spy/tests/test_fqn.py
- spy/tests/test_fqn_parser.py
- spy/vm/astframe.py
- spy/vm/classframe.py
- spy/vm/function.py
- spy/vm/modframe.py
- spy/vm/vm.py
This is easier to explain with an example than with many words:
```python
@blue
def add(T):
def impl(x: T, y: T) -> T:
return x + y
return impl
def foo() -> void:
x = add(i32)(1, 2)
y = add(str)("a", "b")
```
Before this PR, it generated `namespace::add::impl` and `namespace::add::impl#1`.
Now it generates `namespace::add[i32]::impl` and `namespace::add[str]::impl`.
> Add type qualifiers to the namespaces created when invoking blue functions

- spy/backend/spy.py
- spy/tests/test_doppler.py
Fix the spy backend in case we have an assignment to a variable declared in an outer scope (e.g. a global var)
> Fix spy backend

- .gitignore
- spy/backend/c/context.py
- spy/backend/c/cwriter.py
- spy/cli.py
- spy/tests/test_cli.py
- store build artifcations in the `build/` directory, and add `--build-dir` to override that
- generate a .c and a .h for each .spy module
> Split the generated code into .c and .h

- examples/array.spy
- spy/tests/compiler/test_operator.py
- spy/tests/compiler/test_operator_attr.py
- spy/tests/compiler/test_operator_call.py
- spy/tests/conftest.py
- spy/vm/object.py
- spy/vm/opimpl.py
This is a slight departure from Python's semantics: by default, `__new__` doesn't get the class.
This makes a lot of sense after translation, because most of the time the class is not needed.
If a type really wants to do dynamic dispatch depending of the type, it should override `__NEW__`
> Use a simpler signature for applevel __new__

- CLAUDE.md
- examples/array.spy
- spy/ast.py
- spy/backend/c/cwriter.py
- spy/backend/spy.py
- spy/doppler.py
- spy/errors.py
- spy/libspy/__init__.py
- spy/libspy/include/spy/debug.h
- spy/libspy/include/spy/operator.h
- spy/libspy/include/spy/unsafe.h
- spy/libspy/src/debug.c
- spy/libspy/src/str.c
- spy/parser.py
- spy/tests/compiler/test_basic.py
- spy/tests/test_backend_spy.py
- spy/tests/test_doppler.py
- spy/tests/test_libspy.py
- spy/tests/test_parser.py
- spy/tests/vm/test_vm.py
- spy/vm/astframe.py
- spy/vm/function.py
- spy/vm/modules/builtins.py
- spy/vm/modules/operator/__init__.py
- spy/vm/modules/operator/raiseop.py
- spy/vm/modules/unsafe/ptr.py
- spy/vm/object.py
- spy/vm/vm.py
We don't have proper exceptions yet:
- all `raise`s result into a panic (i.e., they cannot be caught)
- to simplify the implementation in the C backend, we support only "blue" exceptions
Moreover, we improve `SPyPanicError` and the C-level implementation of `spy_panic` to takes filename and line number.
The output in case of panic looks like this (and it looks the same both interpreted and compiled):
```
$ spy /tmp/fail.spy 
panic: IndexError: hello
--> /tmp/fail.spy:2:2
2 |     raise IndexError("hello")
|  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
```
> Add support for a very basic version of the raise statement

- examples/array.spy
- examples/blue_generic.spy
- examples/bluefunc.spy
- spy/ast.py
- spy/backend/c/context.py
- spy/backend/c/cwriter.py
- spy/backend/spy.py
- spy/fqn.py
- spy/location.py
- spy/parser.py
- spy/tests/compiler/test_00_bluemod.py
- spy/tests/compiler/test_basic.py
- spy/tests/test_loc.py
- spy/tests/test_parser.py
- spy/tests/vm/test_builtin.py
- spy/tests/vm/test_func_adapter.py
- spy/tests/vm/test_function.py
- spy/vm/astframe.py
- spy/vm/builtin.py
- spy/vm/func_adapter.py
- spy/vm/function.py
- spy/vm/modules/operator/callop.py
- spy/vm/modules/operator/itemop.py
- spy/vm/typechecker.py
`@blue.generic` functions are exactly like `@blue`, but they are "called" using square brackets instead of parenthesis.
This makes it possible to write things like this:
```
@blue.generic
def add(T):
def impl(x:T, y: T) -> T:
return x + y
return impl
def main() -> void:
print(add[i32](1, 2))
print(add[str]('hello ', 'world'))
```
In addition, there are a couple of minor/related updates:
- `W_FuncType` no longer includes argument names, only the argument types
- we have different FQNs for red/blue/blue_generic functions, and we simplified how to generate human-readable versions of them
- improved Loc.get_src to work also in multiline case
- fix error reporting of blue functions with implicit return types (before, funcdef.prototype_loc wrongly pointed to the whole function)
-
> Introduce @blue.generic

- spy/tests/compiler/test_basic.py
- spy/vm/modules/operator/convop.py
This is wrong because it causes a truncation, which we don't want to do implicitly.  It was added by commit de70fbda: it's unclear what was the original goal, but I think it was just a mistake
> disable implicit float-to-int conversion

- spy/analyze/importing.py
- spy/cli.py
- spy/tests/compiler/test_importing.py
- spy/tests/test_importing.py
- spy/vm/vm.py
Now SPy determines the order of imports as it's indicated by `ImportAnalyzer.__doc__`:
https://github.com/spylang/spy/blob/71a6f94d649e2a3db9886b510304ce56db8b90ba/spy/analyze/importing.py#L18-L83
Moreover, this PR adds better pretty printer for `spy --imports`:
> Improve importing logic

- spy/build/cffi.py
- spy/util.py
Fixes #164 
On MacOS there are possibly warning messages printed to stderr when compiling the test c extension. To prevent this from confusing the cffi_build function, change the robust_run function to not redirect stderr to stdout. This allows callers of robust_run to read stdout and stderr separately.
> Fix test_py_cffi on MacOS

- .github/workflows/tests.yml
Add macos-latest as a platform the github tests workflow runs on. 
See here for a list of runners:
https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
> chore: Enable MacOS tests on CI github workflow.

- spy/ast.py
- spy/doppler.py
- spy/libspy/include/spy/str.h
- spy/libspy/src/str.c
- spy/parser.py
- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_builtins.py
- spy/tests/compiler/test_str.py
- spy/tests/test_parser.py
- spy/tests/vm/test_builtin.py
- spy/vm/builtin.py
- spy/vm/function.py
- spy/vm/modules/builtins.py
- spy/vm/modules/operator/callop.py
- spy/vm/registry.py
- spy/vm/str.py
This PR introduces the concept of metafunctions and the `@blue.metafunc` decorator.
Metafunctions are a generalization of the two-phase dispatch concept which is already in place for operators.
Calling a metafunc happens in two step:
1. blue call to the metafunc itself, passing `OpArg` as arguments, and returning and `OpImpl`
2. red call to the returned `OpImpl`
This makes it possible to e.g. implement overloading, and to use it to implement generic functions like `len()` and `print()`.
> Introduce metafunctions

- spy/libspy/include/spy/operator.h
- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_typelift.py
- spy/tests/wasm_wrapper.py
- spy/vm/modules/operator/__init__.py
- spy/vm/modules/operator/binop.py
- spy/vm/modules/operator/opimpl_bool.py
- Add boolean equality operators (`==` and `\!=`)
- Add full set of boolean operations (`and`, `or`, `not`)
This PR implements boolean comparison and operation capabilities, enabling more expressive conditional logic in SPy code.
- Run test suite to verify proper boolean operator functionality
> Add bool operators

- spy/cli.py
- spy/tests/test_cli.py
Old habits die hard, more than once in development I've mistakenly passed a `.py` file to the cli, which will then spit out a long traceback. For the benefit of new users and old, write a helpful message to stderr and exit with an error code if the user asks to process a `.py` file.
Example:
```
$  spy --redshift foo.py 
Error: foo.py is a .py file, not a .spy file.
```
> Give an explanatory error if user passes a .py file to cli.

- spy/tests/compiler/operator/test_attrop.py
- spy/tests/vm/test_builtin.py
- spy/vm/builtin.py
- spy/vm/modules/operator/attrop.py
- spy/vm/modules/types.py
- spy/vm/object.py
- spy/vm/opspec.py
- spy/vm/property.py
- spy/vm/str.py
- spy/vm/vm.py
This is the first a multiple PR to implement the descriptor protocol, only `__get__` for now.
- add support for `__get__`
- introduce `@builtin_property` and `W_Property`
- introduce `@builtin_class_attr
- remove the ugly `__GET_xxx__`, and use `@builtin_property` instead
> Implement the descriptor protocol (__get__)

- spy/tests/compiler/operator/test_attrop.py
- spy/tests/compiler/operator/test_binop.py
- spy/tests/compiler/operator/test_callop.py
- spy/tests/compiler/operator/test_convop.py
- spy/tests/compiler/operator/test_itemop.py
- spy/tests/compiler/operator/test_opimpl.py
- spy/tests/compiler/operator/test_unaryop.py
- spy/tests/vm/test_builtin.py
- spy/tests/vm/test_opimpl.py
- spy/vm/exc.py
- spy/vm/modules/builtins.py
- spy/vm/modules/math.py
- spy/vm/modules/operator/convop.py
- spy/vm/modules/operator/opimpl_bool.py
- spy/vm/modules/operator/opimpl_object.py
- spy/vm/modules/operator/opimpl_str.py
- spy/vm/modules/rawbuffer.py
- spy/vm/opspec.py
- spy/vm/str.py
- spy/vm/vm.py
This PR annotates vm.wrap with better typing, allowing us to kill a lot of "type: ignore" comments
> Better typing for vm.wrap

- spy/tests/compiler/operator/test_attrop.py
- spy/tests/support.py
- spy/vm/object.py
- spy/vm/opspec.py
- spy/vm/vm.py
- Make it possible to actually getattr class attributes from applevel, by implementing `type.__getattr__` (as a metafunc, so we can do a blue lookup)
- Improve `builtin_class_attr` and use it for `OpSpec.NULL`, so we can now kill `W_MetaOpSpec`
> applevel support for class attributes

- spy/tests/compiler/operator/test_attrop.py
- spy/tests/compiler/operator/test_callop.py
- spy/tests/compiler/operator/test_convop.py
- spy/vm/member.py
- spy/vm/modules/operator/attrop.py
- spy/vm/modules/unsafe/ptr.py
- spy/vm/object.py
- spy/vm/opspec.py
- spy/vm/vm.py
- Implement the `__set__` part of the descriptor protocol
- Kill `spy_members`, use normal descriptors instead
- while we were at it, kill `W_PtrType.__GETATTR__` and use a property for `NULL` instead
> Implement __set__, and implement Members using the descriptor protocol

- spy/libspy/include/spy/jsffi.h
- spy/tests/compiler/operator/test_attrop.py
- spy/vm/astframe.py
- spy/vm/module.py
- spy/vm/modules/jsffi.py
- spy/vm/modules/operator/attrop.py
- spy/vm/modules/operator/opimpl_dynamic.py
- spy/vm/modules/unsafe/ptr.py
- spy/vm/object.py
Refactor things to follow CPython's conventions and logic more closely w.r.t. attribute lookup.
This makes it easier to follow SPy's rules, and to understand the differences.
- rename `__getattr__` into `__getattribute__` (the "proper" `__getattr__` is not supported yet)
- rename parameter `attr` into `name` (as in CPython)
- put SPy's default logic into `default_getattribute`: this mimics `PyObject_GenericGetAttr`, but it contains a long comment which explains what are the SPy-specific rules, and the rationale
- implement a much more complete `type.__getattribute__`, which follows closely CPython's equivalent `typeobject.c:type_getattro`.
> Refactor getattribute

- spy/tests/compiler/test_basic.py
- spy/vm/module.py
- spy/vm/modules/operator/callop.py
- spy/vm/vm.py
This PR makes it possible to call module-level functions using the dot notation, like this:
```
import math
print(math.fabs(x))
```
until now, the code above failed because Module didn't implement `__call_method__`.
This is a bit of a hack, though. Ideally, we would like a more generic logic like this:
1. if the type implements `__call_method__`, call it
2. else, fallback to the classic getattr()+call()
However, it's a bit tricky to implement (2) with the tools that we have now. In particular, `W_OpSpec` is not powerful enough to represent a combination of two calls.
> Implement W_Module.__call_method__

- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_metafunc.py
- spy/vm/astframe.py
- spy/vm/function.py
- spy/vm/modules/builtins.py
- spy/vm/modules/operator/callop.py
- spy/vm/typechecker.py
- make sure to generate the correct TypeErrors in case you call a metafunc with wrong arguments or it returns a wrong type
- thanks to metafunc we can remove the special case for STATIC_TYPE and implement it as a normal builtin
> Improve metafunc error reporting and make STATIC_TYPE a normal builtin

- spy/analyze/scope.py
- spy/ast.py
- spy/backend/spy.py
- spy/cli.py
- spy/doppler.py
- spy/fqn.py
- spy/fqn_parser.py
- spy/parser.py
- spy/tests/compiler/test_basic.py
- spy/tests/test_backend_spy.py
- spy/tests/test_cli.py
- spy/tests/test_fqn.py
- spy/tests/test_fqn_parser.py
- spy/tests/test_parser.py
- spy/tests/test_scope.py
- spy/tests/wasm_wrapper.py
- spy/vm/astframe.py
- spy/vm/vm.py
Decorators must be `@blue` functions, but otherwise they work very similarly to Python.
To make debugging easier, the "original" function is named e.g. `mod::foo#__bare__`, so that it's clear that it doesn't necessarily correspond to `mod.foo`.
Moreover, in this PR we modify the class FQN in two ways:
1. make sure it's immutable, and fix a bug which mutated the original FQN when calling `with_suffix`
2. change (again!) the type of `FQN.suffix` from int to str. This is needed to make it possible to use the `__bare__` suffix.
> Add support for decorators

- spy/ast.py
- spy/ast_dump.py
- spy/cli.py
- spy/doppler.py
- spy/tests/test_cli.py
- spy/tests/test_doppler.py
- spy/vm/vm.py
Fixes #168 
I should say first, this is probably a larger PR than you were expecting. I'm totally fine if we abandon this approach and go in a different direction, but I wanted to see what directions I could come up with and if any are useful.
The tl;dr currently is, if you have `foo.spy`:
```
def main(x: i32) -> i32:
return x + 2 * 3
```
Then run:
```
spy --redshift --colorize foo.spy
```
You will see:
This is probably not quite what we were looking for, for one I suspect we don't want the delemiters like () [] colored, or things like the top level Module colored, but the approach is close enough that I wanted to get some feedback first before proceeding in this direction.
I tried to make small atomic commits introducing single concepts at a time:
- In …
> Pretty print AST with color information 

- spy/backend/c/cmodwriter.py
- spy/libspy/include/spy/unsafe.h
- spy/tests/compiler/test_tuple.py
- spy/tests/stdlib/test_array.py
- spy/vm/tuple.py
- stdlib/array.spy
This PR introduces the first stdlib module: `stdlib/array.spy` 🎉.
So far arrays are very limited:
- only 1, 2 and 3 dimensions (eventually we will be able to have arbitraty n-dimension for any `blue` value of `n`)
- only getitem, setitem and `from_buffer
> Introduce stdlib/array.spy

- spy/analyze/scope.py
- spy/analyze/symtable.py
- spy/ast.py
- spy/backend/spy.py
- spy/build/config.py
- spy/build/ninja.py
- spy/cli.py
- spy/doppler.py
- spy/parser.py
- spy/tests/compiler/test_basic.py
- spy/tests/compiler/test_struct.py
- spy/tests/stdlib/test__range.py
- spy/tests/test_parser.py
- spy/tests/test_scope.py
- spy/tests/wasm_wrapper.py
- spy/vm/astframe.py
- spy/vm/modules/builtins.py
- spy/vm/struct.py
- spy/vm/vm.py
- stdlib/_range.spy
This PR implements support for `for` loops in the parser, ScopeAnalyzer and ASTFrame. For loops don't use the classical `__iter__` protocol as in Python. Instead, they use a new protocol called `__fastiter__`, which is stateless and thus easier to optimize for the compiler.
In ASTFrame, the `for` loop is desugared into the equivalent `while`: thanks to this, DopplerFrame and the C backend mostly work out of the box.
Moreover, this PR also introduces the `range` object, implemented in pure spy in `stdlib/_range.spy`. Currently it is not automatically available as a builtin because we don't have the machinery to import spy code as part of builtins.
Enable LTO when compiling in release mode: this is necessary to ensure that gcc is able to inline the methods of the `__fastiter__` protocol and …
> For loops, range and iterators

- spy/analyze/importing.py
- spy/cli.py
- spy/tests/test_importing.py
- spy/vm/vm.py
Reading through the code, I encountered a misspelled variable name `ImportAnalizyer`. It was tugging on my brain enough that I thought I'd put up a PR to fix it. 😄
> Fix misspelling ImportAnalizyer to ImportAnalyzer
